@startuml
class App
{
    + main()
}
class Test
{
    - outputNames()
}
class Names
{
    +class sortNames()
}
Test-->App: Sends Sorted array of names.
Names-->Test: Sends String array of names.
@enduml